#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| 註冊自動載入器
|--------------------------------------------------------------------------
|
| Composer提供了一個方便的、自動產生的類別載入器
| 對於這個應用程式。我們只需要使用它！我們將簡單地要求它
| 進入腳本，這樣我們就不必手動載入任何類別。
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| 執行Artisan應用程式
|--------------------------------------------------------------------------
|
| 當我們執行控制台應用程式時，目前的CLI命令將被執行
| 在此控制台中，並將回應傳送回終端機
| 所以開發者可以接收回饋。
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| 關閉應用程式
|--------------------------------------------------------------------------
|
| 一旦Artisan完成執行，我們將觸發關閉事件，以便
| 任何最終工作都可以由應用程式完成，然後我們將
| 退出程序並返回CLI的適當回應碼。
|
*/

$kernel->terminate($input, $status);

exit($status);