# Docker Compose生產環境設定

version: '3.8'

services:
  # 生產環境的Nginx設定
  nginx:
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./docker/nginx/ssl/:/etc/nginx/ssl/:ro
      - nginx_logs:/var/log/nginx
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # 生產環境的Laravel設定
  laravel:
    build:
      args:
        - APP_ENV=production
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
      - php_logs:/var/log
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=warning
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # 生產環境的資料庫設定
  database:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=1G

  # 生產環境的Redis設定
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # 移除開發工具
  phpmyadmin:
    profiles:
      - development

  mailpit:
    profiles:
      - development